### PR TITLE
upgrade to sbt 1.4

### PR DESCRIPTION
**Pull request by SethTisue**
I'm interested in seeing if your CI gives the same failure
that we saw at https://github.com/scala/community-build/pull/1211

### CODE REVIEW

**Comment by SethTisue** [comment]
hmm, CI likes it. okay, up to you if you want to close this and wait for sbt 1.4.0 final

**Comment by SethTisue** [comment]
hmm, https://github.com/scala/community-build/pull/1211#issuecomment-689037404

**Review by olafurpg — APPROVED** [review]
LGTM 👍 Thank you!

**Comment by olafurpg** [comment]
I'm loving sbt 1.4, the new tab completions are amazing and the new BSP support is really promising!

**Comment by SethTisue** [comment]
reverted at https://github.com/scalameta/munit/issues/210 for Dotty-related reasons, we can try again later :-)

**Pull request merged**
