### PR TITLE
Cross-build against latest Scala 3 milestone release.

### LINKED ISSUE #263: 3.0.0-M2 release
Scalacheck was just published so munit should be ready.

### PR DESCRIPTION
**Pull request by olafurpg**
Fixes #263

### CODE REVIEW

**Comment by olafurpg** [comment]
There are some compile errors 
```
[error] -- [E006] Not Found Error: /Users/lgeirsson/dev/munit/munit/shared/src/main/scala-3/munit/internal/MacroCompat.scala:13:33
[error] 13 |  def locationImpl()(using qctx: QuoteContext): Expr[Location] = {
[error]    |                                 ^^^^^^^^^^^^
[error]    |                                 Not found: type QuoteContext
[error] -- [E006] Not Found Error: /Users/lgeirsson/dev/munit/munit/shared/src/main/scala-3/munit/internal/MacroCompat.scala:24:51
[error] 24 |  def clueImpl[T:Type](value: Expr[T])(using qctx: QuoteContext): Expr[Clue[T]] = {
[error]    |                                                   ^^^^^^^^^^^^
[error]    |                                            Not found: type QuoteContext
[error] -- [E049] Reference Error: /Users/lgeirsson/dev/munit/munit/shared/src/main/scala-3/munit/internal/MacroCompat.scala:26:17
[error] 26 |    val source = value.unseal.pos.sourceCode
[error]    |                 ^^^^^
[error]    |Reference to value is ambiguous,
[error]    |it is both defined in method clueImpl
[error]    |and imported subsequently by import (qctx.tasty : <error Not found: type QuoteContext>).{...}
[error] -- [E053] Type Error: /Users/lgeirsson/dev/munit/munit/shared/src/main/scala-3/munit/internal/MacroCompat.scala:27:31
[error] 27 |    val valueType = implicitly[scala.quoted.Type[T]].show
[error]    |                               ^^^^^^^^^^^^^^^^^^^^
[error]    |              qctx.tasty.scala.quoted.Type does not take type parameters
[error] -- [E049] Reference Error: /Users/lgeirsson/dev/munit/munit/shared/src/main/scala-3/munit/internal/MacroCompat.scala:28:34
[error] 28 |    '{ new Clue(${Expr(source)}, $value, ${Expr(valueType)}) }
[error]    |                                  ^^^^^
```

Is there any documentation on the breaking changes? I wasn't able to find any at https://github.com/lampepfl/dotty/releases/tag/3.0.0-M2 or http://dotty.epfl.ch/blog/index.html

**Comment by gabro** [comment]
@olafurpg one "trick" we can use in these situations is to look at the munit fork in the dotty community build https://github.com/dotty-staging/munit/

**Comment by gabro** [comment]
https://github.com/dotty-staging/munit/commit/e26d260c1d0b11aeca7c353516005ad5903029e8

https://github.com/dotty-staging/munit/commit/84325e516d47401c735a8a5132d1763d75033ce8

https://github.com/dotty-staging/munit/commit/b32f594f3bcd78e4784439fb7099939ac3b5eb68

These three commits look relevant, let me know if you have time to backport this yourself, otherwise I can do it

**Comment by olafurpg** [comment]
@gabro that was the trick I was missing! If you have time to look into this then that would be great.

**Comment by gabro** [comment]
Done in #265

**Pull request closed without merging**
