### PR TITLE
Update test-release.sh to latest dotty

### PR DESCRIPTION
**Pull request by gabro**
Followup from #168

### CODE REVIEW

**Comment by gabro** [comment]
@tgodzik / @olafurpg I'm thinking to release 0.7.10 with dotty 0.26-RC1 support after merging this.

This would also drop support for 0.24 (keeping support for the latest stable and the latest RC, as usual).

Any objection?

**Comment by gabro** [comment]
I just saw @olafurpg message on Gitter, I'll go ahead with it

**Comment by tgodzik** [comment]
I haven't noticed the script. Sorry!

**Comment by gabro** [comment]
Absolutely not a big deal :-)

**Pull request merged**
