### PR TITLE
ScalaCheck 1.15.0

### PR DESCRIPTION
**Pull request by larsrh**
Scalacheck is natively built for Dotty.

Since 1.15.0 (and other releases in the 1.15.x series) are binary compatible to 1.14.0, the transition should be smooth.

~1.15.0 final should follow after RC1 next week. I've opened this PR with the RC to figure out if there are any remaining issues with it.~

### CODE REVIEW

**Comment by larsrh** [comment]
Scalacheck is built with Scala.js 1.3.0. Can we bump this here, too?

**Comment by olafurpg** [comment]
Thank you for this contribution! It's OK to bump up Scala.js. Users who can't upgrade to Scala.js 1.3.x can stay on older versions of MUnit until they complete the upgrade.

**Comment by larsrh** [comment]
Done.

**Comment by larsrh** [comment]
Updated & rebased for 1.15.0 final.

**Review by olafurpg — APPROVED** [review]
LGTM 👍 Thank you!

**Comment by olafurpg** [comment]
https://github.com/scalameta/munit/releases/tag/v0.7.15

Manged to include this change in the last 0.7.x release before we merge #225 and start iterating on v1.x milestones.

**Comment by larsrh** [comment]
Amazing! The Dotty release train running full steam ahead 🚂

**Pull request merged**
